spring:
  datasource:
    username: root
    password: Asdfzxcv123!mysql
    url: jdbc:mysql://192.168.2.144:3306/spring04mybatis?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver